---
title: "Parallelization of SCENT"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Parallelization of SCENT}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load Package

```{r setup}
library(SCENT)
```

## Data Inputs

```{r}
#Initialize directories: (Example)
input_atac <- "./RData/Data/pbmc_multimodal.atac.rds"
input_mrna <- "./RData/Data/pbmc_multimodal.rna.rds"
input_meta <- "./RData/Data/pbmc_multimodal.meta.rds"
input_gene_peak <- "./RData/Data/qced_Tnk.G2P.txt"
output_rds <- "./Output/SCENT_obj.rds"
####Obtaining Gene-Peak Pairs using defined bed file
genebed_loc <- "./RData/Data/GeneBody_500kb_margin_chr.bed" 


options(stringsAsFactors = F)

#Read-in Necessary Files:
atac <- readRDS(input_atac)
mrna <- readRDS(input_mrna)
meta <- readRDS(input_meta)
gene_peak <- read.table(input_gene_peak)
colnames(gene_peak) <- c("gene","peak")
```



## SCENT Object

```{r SCENT}
####Using the SCENT Object:
SCENT_obj <- CreateSCENTObj(rna = mrna, atac = atac, meta.data = meta,
                            covariates = c("log(nCount_RNA)","percent.mito"), 
                            celltypes = "newCT")
str(SCENT_obj)
```

## Make Gene-Peak Pair Lists

```{r}
SCENT_obj <- CreatePeakToGeneList(SCENT_obj, genebed = genebed_loc,
                                  nbatch = 1000,tmpfile="./temporary_atac_peak.bed",
                                  intersectedfile="./temporary_atac_peak_intersected.bed.gz")
str(SCENT_obj, max.level = 2)
```

##Save the SCENT obj for parallelized jobs on the cluster to get SCENT results.

```{r}
saveRDS(SCENT_obj, file = output_rds) #Takes a couple minutes.
```

## Use the saved SCENT_obj to run a parallelized bash script: Located in "Parallelized Bash Script" Folder

```
