---
title: "SCENT_interactive"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SCENT_interactive}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load Package

```{r setup}
library(SCENT)
```

## Load Inputs

```{r}
#Initialize directories: (Example)
input_atac <- "./RData/Data/pbmc_multimodal.atac.rds"
input_mrna <- "./RData/Data/pbmc_multimodal.rna.rds"
input_meta <- "./RData/Data/pbmc_multimodal.meta.rds"
input_gene_peak <- "./RData/Data/qced_Tnk.G2P.txt"
output <- "./Output/test_output.txt"

options(stringsAsFactors = F)

#Read-in Necessary Files:
atac <- readRDS(input_atac)
mrna <- readRDS(input_mrna)
meta <- readRDS(input_meta)
gene_peak <- read.table(input_gene_peak)
colnames(gene_peak) <- c("gene","peak")

```

## SCENT Object

```{r SCENT}
##Using the SCENT Object:
SCENT_obj <- CreateSCENTObj(rna = mrna, atac = atac, meta.data = meta,
                            peak.info = gene_peak,
                            covariates = c("log(nCount_RNA)","percent.mito"), 
                            celltypes = "newCT")

##Example Outputs of the SCENT Object
head(SCENT_obj@rna[1:10,1:2])
head(SCENT_obj@atac[1:10,1:2])
head(SCENT_obj@meta.data)
head(SCENT_obj@peak.info)
str(SCENT_obj)
```

## SCENT Algorithm: Obtain small list of gene-peak pairs.

```{r gene_peak}
#Of the set of peak gene pairs: pick a set of pairs to test: 
#Example: (first 10 gene-peak pairs)
SCENT_obj@peak.info <- SCENT_obj@peak.info[1:10,]
head(SCENT_obj@peak.info)
```
## SCENT Algorithm: Options for Regression w/ Bootstrapping.

```{r gene_peak}
#Run SCENT algorithm of Tnk cell type and use 6 cores for parallelization:


#Default: Poisson regression and Binarized ATAC counts
SCENT_obj_ver1 <- SCENT_algorithm(SCENT_obj, "Tnk", 6) 
# By default settings the above will perform parallelizations using Poisson regression and Binarized counts.

#Option 1: Poisson regression and Non-Binarized ATAC counts
SCENT_obj_ver2 <- SCENT_algorithm(SCENT_obj, "Tnk", 6, regr = "poisson", bin = FALSE)

#Option 2: Negative Binomial regression and Binarized ATAC counts
SCENT_obj_ver3 <- SCENT_algorithm(SCENT_obj, "Tnk", 6, regr = "negbin", bin = TRUE)

#Option 3: Negative Binomial regression and Non-Binarized ATAC counts
SCENT_obj_ver4 <- SCENT_algorithm(SCENT_obj, "Tnk", 6, regr = "negbin", bin = FALSE)

```

## Output of SCENT Algorithm

```{r SCENT_algo}
head(SCENT_obj_ver1@SCENT.result)
head(SCENT_obj_ver2@SCENT.result)
head(SCENT_obj_ver3@SCENT.result)
head(SCENT_obj_ver4@SCENT.result)
```

```

